apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: skaffold-demo
build:
  artifacts:
    - image: skaffold-demo
      jib:
        project: org.jack.skaffold:skaffold-demo
manifests:
  rawYaml:
    - k8s/skaffold-demo-deployment.yaml
    - k8s/skaffold-demo-service.yaml
