apiVersion: apps/v1
kind: Deployment
metadata:
  name: skaffold-demo
  labels:
    app: skaffold-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skaffold-demo
  template:
    metadata:
      name: skaffold-demo
      labels:
        app: skaffold-demo
    spec:
      containers:
        - name: skaffold-demo
          image: skaffold-demo
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8800
              protocol: TCP
      restartPolicy: Always
      